import { CMSData } from './types';

export const INITIAL_CMS_DATA: CMSData = {
  hero: {
    nama: 'Alya Pratama',
    namaPendek: 'AYA',
    kalimatPembuka: 'Halo, saya Alya Pratama alias AYA',
    headlineUtama: 'Creative',
    headlineKedua: 'Designer',
    visualText: 'Visual',
    fotoProfile: '', // Empty means using standard SVG portrait as default
    statistikPengalaman: 5,
    statistikJumlahProject: 60,
    badges: [
      {
        id: 'b1',
        nama: 'Brand Designer',
        warnaBackground: 'mint',
        warnaText: '#1b1c23',
        posisi: 1,
        visibility: true,
      },
      {
        id: 'b2',
        nama: 'Product Designer',
        warnaBackground: 'coral',
        warnaText: '#1b1c23',
        posisi: 2,
        visibility: true,
      },
      {
        id: 'b3',
        nama: 'UI/UX Designer',
        warnaBackground: 'violet',
        warnaText: '#1b1c23',
        posisi: 3,
        visibility: true,
      },
    ],
    heroBackground: {
      image: null,
      positionX: 50,
      positionY: 50,
      scale: 100,
      opacity: 40,
      brightness: 100,
      contrast: 100,
      blur: 0,
      overlayOpacity: 30,
      overlayColor: '#1b1c23',
    },
  },
  profile: {
    nama: 'Alya Pratama',
    deskripsi: 'Saya membuat antarmuka yang tidak konvensional namun fungsional dan enak dipakai, untuk mobile dan web.',
    bio: 'Desainer produk yang senang merancang pengalaman digital yang terasa sederhana dan hidup. Dengan latar belakang desain grafis dan riset pengguna, saya menerjemahkan ide menjadi antarmuka yang intuitif dan indah dipakai. Pendekatan saya berakar pada empati, ketelitian pada detail, dan komitmen untuk terus belajar.',
    fotoProfil: '',
    cvSummary: 'Desainer Visual & Produk dengan 5+ tahun pengalaman dalam membangun aplikasi mobile, sistem informasi, dan brand digital.',
    highlights: [
      'Senior Product Designer — Creative Studio (2023 - Sekarang)',
      'UI/UX Designer — Digital Agency (2021 - 2023)',
      'Visual Designer — Freelance & Open Source (2019 - 2021)',
    ],
    informasiProfesional: [
      { key: 'Keahlian', value: 'Figma, UI Animation, Design Systems, User Research, Mobile App Design' },
      { key: 'Bahasa', value: 'Bahasa Indonesia (Native), English (Professional)' },
      { key: 'Lokasi', value: 'Jakarta, Indonesia (Available for Remote/Hybrid)' },
    ],
  },
  skills: [
    {
      id: 's1',
      nama: 'Figma & Design Systems',
      kategori: 'Design',
      level: 95,
      icon: 'Palette',
      deskripsi: 'Merancang komponen reusable, variable, auto-layout, dan library berskala besar.',
      urutan: 1,
      status: 'PUBLISHED',
    },
    {
      id: 's2',
      nama: 'UI Animation',
      kategori: 'Design',
      level: 88,
      icon: 'Activity',
      deskripsi: 'Membuat animasi transisi mikro dan prototype interaktif berpresisi tinggi.',
      urutan: 2,
      status: 'PUBLISHED',
    },
    {
      id: 's3',
      nama: 'User Research & Wireframing',
      kategori: 'Research',
      level: 82,
      icon: 'Search',
      deskripsi: 'Melakukan wawancara pengguna, usability testing, dan pemetaan alur pengguna.',
      urutan: 3,
      status: 'PUBLISHED',
    },
    {
      id: 's4',
      nama: 'React & Tailwind CSS',
      kategori: 'Development',
      level: 78,
      icon: 'Code2',
      deskripsi: 'Mengimplementasikan UI design ke dalam baris kode frontend modern yang responsif.',
      urutan: 4,
      status: 'PUBLISHED',
    },
  ],
  portfolio: [
    {
      id: 'p1',
      judul: 'Kopi Senja App',
      slug: 'kopi-senja-app',
      kategori: 'Mobile App',
      thumbnail: 'green-phone', // special layout tag
      cover: 'green-phone',
      gallery: [],
      deskripsi: 'Proyek Kopi Senja App berfokus pada perancangan sistem visual, pengalaman pengguna yang intuitif, serta arsitektur antarmuka modern yang fungsional.',
      client: 'Kopi Senja Co.',
      tahun: 2024,
      role: 'Lead Visual & UI/UX Designer',
      tools: ['Figma', 'Prototyping', 'Design System'],
      projectURL: 'https://kopisenja.example.com',
      prototypeURL: 'https://figma.example.com/kopi-senja',
      status: 'PUBLISHED',
      urutan: 1,
    },
    {
      id: 'p2',
      judul: 'Rumah Denim',
      slug: 'rumah-denim',
      kategori: 'E-Commerce Website',
      thumbnail: 'blue-layers',
      cover: 'blue-layers',
      gallery: [],
      deskripsi: 'Website e-commerce premium untuk produk denim berkualitas tinggi, mengedepankan editorial visual yang estetik dan minimalis.',
      client: 'Rumah Denim Inc.',
      tahun: 2023,
      role: 'UI Designer & Brand Strategy',
      tools: ['Figma', 'UI Animation', 'Tailwind CSS'],
      projectURL: 'https://rumahdenim.example.com',
      prototypeURL: '',
      status: 'PUBLISHED',
      urutan: 2,
    },
    {
      id: 'p3',
      judul: 'Portal Iklim Daerah',
      slug: 'portal-iklim-daerah',
      kategori: 'Sistem Informasi',
      thumbnail: 'gold-charts',
      cover: 'gold-charts',
      gallery: [],
      deskripsi: 'Sistem informasi pemantauan iklim, kualitas udara, dan kelestarian lingkungan hidup regional secara real-time dan interaktif.',
      client: 'Badan Lingkungan Hidup',
      tahun: 2024,
      role: 'Lead Dashboard & UI Designer',
      tools: ['Data Visualization', 'Figma', 'React'],
      projectURL: 'https://iklim.example.org',
      prototypeURL: '',
      status: 'PUBLISHED',
      urutan: 3,
    },
    {
      id: 'p4',
      judul: 'Kelas Pintar',
      slug: 'kelas-pintar',
      kategori: 'EdTech App',
      thumbnail: 'blue-laptop',
      cover: 'blue-laptop',
      gallery: [],
      deskripsi: 'Platform mobile pembelajaran interaktif untuk anak sekolah dengan gamifikasi dan visual learning yang menyenangkan.',
      client: 'Yayasan Indonesia Pintar',
      tahun: 2023,
      role: 'Product Designer',
      tools: ['User Research', 'Mobile Layout', 'Figma'],
      projectURL: '',
      prototypeURL: 'https://figma.example.com/kelas-pintar',
      status: 'PUBLISHED',
      urutan: 4,
    },
  ],
  hasilKarya: [
    {
      id: 'k1',
      judul: 'Senja Mountains Contour',
      kategori: 'ilustrasi',
      gambar: 'scenery-card', // matches the sunset card
      deskripsi: 'Karya seni pemandangan gunung dengan gradasi warna langit senja yang menenangkan.',
      tahun: 2024,
      tools: 'Adobe Illustrator',
      link: '',
      urutan: 1,
      status: 'PUBLISHED',
    },
    {
      id: 'k2',
      judul: 'Organic Geometry Pattern',
      kategori: 'mockup',
      gambar: 'contour-card', // matches card 2
      deskripsi: 'Eksperimen pola geometris elips berlapis untuk desain packaging premium.',
      tahun: 2023,
      tools: 'Figma',
      link: '',
      urutan: 2,
      status: 'PUBLISHED',
    },
    {
      id: 'k3',
      judul: 'Neon Phone Interface',
      kategori: 'UI design',
      gambar: 'phone-card', // matches card 1
      deskripsi: 'Eksplorasi antarmuka ponsel bernuansa gradasi cerah neon dengan dark background.',
      tahun: 2024,
      tools: 'Figma, Spline',
      link: '',
      urutan: 3,
      status: 'PUBLISHED',
    },
  ],
  prosesKerja: [
    {
      id: 'pk1',
      nomor: '01',
      judul: 'Pahami',
      deskripsi: 'Riset pengguna / Wawancara mendalam',
      icon: 'HelpCircle',
      urutan: 1,
      status: 'PUBLISHED',
    },
    {
      id: 'pk2',
      nomor: '02',
      judul: 'Rumuskan',
      deskripsi: 'User story / Alur pengguna',
      icon: 'Compass',
      urutan: 2,
      status: 'PUBLISHED',
    },
    {
      id: 'pk3',
      nomor: '03',
      judul: 'Rancang',
      deskripsi: 'Panduan gaya / Wireframe & prototipe',
      icon: 'Layers',
      urutan: 3,
      status: 'PUBLISHED',
    },
    {
      id: 'pk4',
      nomor: '04',
      judul: 'Serahkan',
      deskripsi: 'Handoff ke developer / Uji kegunaan',
      icon: 'CheckCircle2',
      urutan: 4,
      status: 'PUBLISHED',
    },
  ],
  kontak: {
    email: 'halo@namakamu.com',
    telepon: '+62 812-0000-0000',
    whatsapp: '6281200000000',
    ctaUtama: 'Kirim pesan',
    ctaKedua: 'Diskusi proyek',
    teksKontak: 'Ayo bekerja sama.',
  },
  sosialMedia: [
    {
      id: 'sm1',
      nama: 'Instagram',
      username: '@namakamu',
      URL: 'https://instagram.com',
      icon: 'instagram',
      urutan: 1,
      visibility: true,
    },
    {
      id: 'sm2',
      nama: 'LinkedIn',
      username: '/in/namakamu',
      URL: 'https://linkedin.com',
      icon: 'linkedin',
      urutan: 2,
      visibility: true,
    },
    {
      id: 'sm3',
      nama: 'Behance',
      username: '/namakamu',
      URL: 'https://behance.net',
      icon: 'behance',
      urutan: 3,
      visibility: true,
    },
    {
      id: 'sm4',
      nama: 'Dribbble',
      username: '/namakamu',
      URL: 'https://dribbble.com',
      icon: 'dribbble',
      urutan: 4,
      visibility: true,
    },
  ],
  mediaLibrary: [
    {
      id: 'ml1',
      name: 'avatar_alya.png',
      type: 'image/png',
      size: 142000,
      uploadDate: '2026-09-21',
      url: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400',
      inUse: true,
    },
    {
      id: 'ml2',
      name: 'coffee_app_thumbnail.png',
      type: 'image/png',
      size: 423000,
      uploadDate: '2026-09-20',
      url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93?auto=format&fit=crop&q=80&w=400',
      inUse: true,
    },
    {
      id: 'ml3',
      name: 'resume_alya_pratama.pdf',
      type: 'application/pdf',
      size: 1045000,
      uploadDate: '2026-09-18',
      url: '#',
      inUse: true,
    },
  ],
  background: {
    type: 'solid',
    solidColor: '#1b1c23',
    gradientColors: '#1b1c23, #23242c',
    image: '',
    video: '',
    position: 'center',
    size: 'cover',
    opacity: 100,
    blur: 0,
    brightness: 100,
    contrast: 100,
    overlay: 'rgba(27, 28, 35, 0.4)',
  },
  appearance: {
    backgroundColor: '#1b1c23',
    secondaryBackground: '#23242c',
    textColor: '#f6f6f8',
    mutedText: '#8e8f9b',
    accentColor: '#25d0a4',
    borderColor: '#3a3b45',
    borderRadius: '12px',
    typographyWeight: '300',
  },
  motion: {
    enabled: true,
    speed: 1,
    revealIntensity: 1,
    blurIntensity: 1,
    parallaxIntensity: 1,
    hoverMovement: 1,
    pageTransition: 'fade',
  },
};
